### ISSUE TITLE
How to backup and restore?

### ISSUE THREAD

**Issue by Extarys** [jcs/rubywarden#101]
Since I'm running this on a Pi with other services, I want to make sure I do this right so I don't lose my passwords!

Can I just copy the db folder, reinstall Rubywarden and copy the backup db over the original one? How does this work?
I realized today I do not have any cronjob to backup my passwords.

What is the suggested way of backing them up?

**Comment by jcs** [comment]
Yes, the `db/production/production.sqlite3` file is all you need to backup and restore.

**Comment by Extarys** [comment]
Ok thanks for confirming, I didn't want to mess that up!
