### ISSUE TITLE
CORS for new Safari Extension

### ISSUE THREAD

**Issue by universal** [jcs/rubywarden#103]
It appears the new bitwarden extension for safari needs some CORS stuff. I'm still figuring things out and need to find my old macbook and have a look. 

## worth looking into
 * https://github.com/jdesrosiers/sinatra-cors

**Comment by markfoodyburton** [comment]
Have same problem

**Comment by universal** [comment]
since my old macbook only has high sierra available I wasn't able to test anything mac specific over the weekend. I might find some time this weekend.

**Comment by markfoodyburton** [comment]
FWIW I'm stuck on High Sierra too.

**Comment by raufis27** [comment]
What we gonna do about this ? "An error has occurred
Preflight response is not successful" < Safari extension.

**Comment by jcs** [comment]
Please try c7c9667 and see if it fixes the Safari extension for you.

**Comment by universal** [comment]
I deployed this and my brother, who is using a mac / safari, reported that it is working again :-) thanks for the work!

**Comment by manojchandrashekar** [comment]
I am seeing this again. Also mentioned here: https://github.com/bitwarden/browser/issues/1140

And the code above is already in the latest release. `lib/app.rb`.
