### ISSUE TITLE
Provide procedure to implement HTTPS

### ISSUE THREAD

**Issue by rei-vilo** [jcs/rubywarden#112]
I've installed Rubywarden on a Raspberry Pi. The native macOS Bitwarden connects successfully although through `http`. However, the Bitwarden extension for Safari and the iOS app seem to require an `https` connection. 

Unfortunately, I wasn't able to set `https` on my Raspberry Pi. Apache is already running with `https` enabled on my Raspberry Pi.

I went through #97, https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension and https://wp-mix.com/htaccess-redirect-http-to-https/, among other solutions from https://serverfault.com and https://httpd.apache.org/docs/, to no avail.

Would it be possible to release a procedure or provide a pointer to implement `https`?

Thank you!

## Configuration

+ Server side: Rubywarden from GitHub April 2, 2020 on Raspbian Buster Lite
+ Client side: Bitwarden 1.17.2 on macOS 15.14, Bitwarden 2.3.1 on iOS 13.4

**Comment by IchSchreiGleich** [comment]
You could configure an virtual host in apache and then "ProxyPass" and "ProxyReverse" requests from and to localhost:4567 - So i did in my configuration.

**Comment by bsilvereagle** [comment]
There are some pointers here, as well as an explanation to make the https connection compatible with the iOS app: 

https://frdmtoplay.com/self-hosting-bitwarden-on-a-beagle-bone-black/
