### ISSUE TITLE
Error when importing passwords from KeePass

### ISSUE THREAD

**Issue by CollinAlpert** [jcs/rubywarden#113]
When importing my data from a KeePass file, I am greeted with the following exception:
![image](https://user-images.githubusercontent.com/14217185/81103971-1b64de00-8f12-11ea-8057-b737999dd641.png)

`rubeepass` is definitely installed in my gems so I have no idea what could be causing this. Is there any more data I need to provide?

**Comment by jcs** [comment]
Does it work after doing `bundle install --with keepass`?

**Comment by CollinAlpert** [comment]
Awesome, that worked, thanks! Would you mind updating the README?

**Comment by jcs** [comment]
It's already in there:

https://github.com/jcs/rubywarden/blame/master/README.md#L189-L190

**Comment by CollinAlpert** [comment]
Well this is embarrassing...sorry 'bout that!
