### ISSUE TITLE
DEBUG messages

### ISSUE THREAD

**Issue by markfoodyburton** [jcs/rubywarden#114]
I get a lot of messages of the form:
DEBUG -- :   #033[1m#033[36mAttachment Load (0.3ms)#033[0m  #033[1m#033[34mSELECT "attachments".* FROM "attachments" WHERE "attachments"."cipher_uuid" = ....
in my logs. 

Actually there are no attachments to load.

Is there a way to remove these debug messages?

**Comment by jcs** [comment]
Those should only appear if you are not using `RUBYWARDEN_ENV=production`
