### ISSUE TITLE
404 error when deleting entry

### ISSUE THREAD

**Issue by CollinAlpert** [jcs/rubywarden#115]
When deleting an item in the Bitwarden Linux app, the call `"PUT /api/ciphers/949c2a6e-b295-498a-8af3-2c4a1e2bbd7c/delete HTTP/1.1" 404 60 0.0044` is made. Evidently, a 404 error code is returned and the entry is not deleted. I just previously restored my passwords from a backup of the `production.sqlite3` file, in case that helps.

**Comment by heggink** [comment]
Same happens with me on the windows app and chrome plugin. Can't seem to be able to delete any entries... rubywarden running under freenas jail.

**Comment by omega123456** [comment]
Same here. It started happening after the recent update of the client. Looks like rubywarden needs updating to work with the latest version of the app.

**Comment by heggink** [comment]
just downgraded the plugin to 1.43. Can delete entries again. in 1.44, there was an change to soft delete entries. maybe related.

**Comment by halukunal** [comment]
#117 I added new delete route support.

**Comment by heggink** [comment]
Excellent! Thanks.
