### ISSUE TITLE
Invalid master password when unlocking desktop client

### ISSUE THREAD

**Issue by baddwin** [jcs/rubywarden#121]
It seems there's a change on latest official Bitwarden that makes the desktop client cannot unlock session and return error "Invalid master password".
There's a discussion here: https://community.bitwarden.com/t/cant-unlock-desktop-client-with-master-password-after-1-20/13728

I don't know whether you're working on this now.

**Comment by jcs** [comment]
I'm [no longer working on this](https://github.com/jcs/rubywarden/issues/122).

**Comment by jcs** [comment]
This should be fixed in 4230e07a
