### ISSUE TITLE
Add file store feature

### ISSUE THREAD

**Issue by Pschittt** [jcs/rubywarden#22]
Hello,

Bitwarden upstream can store file/attachment into a cypher entry, like keepass does.
It could be a ssh key for exemple.

Currently, the API cannot store files/attachments into the sqlite db.

**Comment by universal** [comment]
I'm currently contemplating of switching to bitwarden from 1password and file attachments would be very nice. Currently I've a dummy setup locally, and only tried the Chrome extension, and I couldn't find a file entry there. I also had a quick look at the offical webapp/account, where file attachments are a premium feature. So I don't know if the attachments only work in the web-client, or also show up in the browser extensions. 

If anyone has some pointers, I could take a stab at adding support for this.

**Comment by gregf** [comment]
File attachments are the one thing keeping me from leaving the official server which is really bloated. I mean 6gb ram for a bitwarden server? Craziness.

**Comment by universal** [comment]
I documented the relevant api methods in f3f89d2597d3f7777b8a1e6164ffaf10f6163af1
I did an initial stab at implementing it, but I'm not yet done, and since I did the work based of the pull request #26 I'll just link to the commit with the current wip: ce4d008c8a992ba884cef3a7858e9eb08ccfb4d6

**Comment by universal** [comment]
I've the basic implementation done, it surely can be improved a lot. It still misses the specs and since I've based it off my restructure branch, I'm not submitting a pull request just yet.

It also doesn't clean up the files if you directly delete the cipher, and it still has attachments.

If anyone wants to take a look: https://github.com/universal/bitwarden-ruby/tree/attachments

**Comment by universal** [comment]
The only missing thing now is a human_file_size method. I squashed the commits in this branch: https://github.com/universal/bitwarden-ruby/tree/attachments_squashed . Once the pull request about modularizing the code(#26 ) has been handled in some way, I will adopt this code accordingly and then submit another pull request for the file store functionality.

**Comment by krystiansliwa** [comment]
@universal Hi, when do you plan to make PR for that feature?

**Comment by universal** [comment]
@krystiansliwa Once the pull request about active-record #44 has been handled, I'll submit a pull request.

**Comment by universal** [comment]
there is a second pull-request #52 , which includes active-record and storage support. I'm using this branch personally and it works fine for me using either Chrome/Firefox or the iOs App.

**Comment by universal** [comment]
just for reference: see #65
