### ISSUE TITLE
Export db from command line

### ISSUE THREAD

**Issue by linktohack** [jcs/rubywarden#38]
https://github.com/jcs/bitwarden-ruby/issues/32 makes me think think that it should be safer to have  an option to export the whole db in case the extensions/mobile apps stop working again. (Again, huge thanks to @kspearrin for warning us.)

I suggest that we keep the bitwarden format, basically reverse of https://github.com/jcs/bitwarden-ruby/blob/master/tools/bitwarden_import.rb

**Comment by linktohack** [comment]
Just FYI, the extensions (at least in Chrome) do support exporting now so you can close the issue. Just remember to do an export from time to time...

Thanks again for this repo (especially the idea) @jcs

**Comment by kspearrin** [comment]
The official Bitwarden CLI supports exports and imports. Not sure if they work with this server though...

See https://help.bitwarden.com/article/cli/#import

**Comment by linktohack** [comment]
The reason behind this issue is that we did not have the web interface at that time but rely 100% on the extensions. We needed an option to opt-out if one day the extensions stop working (did happen, thank you for your warning that day.)

One solution like your suggestion is to pack this server with a pinned version of your official web interface.

Anyway, great works with Bitwarden, both as official product and API as a standard. Thanks!

— QL
