### ISSUE TITLE
Web Vault doesn't work 

### ISSUE THREAD

**Issue by raufis27** [jcs/rubywarden#42]
Any plans to make api compatible ?

**Comment by mprasil** [comment]
Hey, @universal is working on this, there was a pull request #37 for that, but it looks like there are some issues to solve after the new API was introduced.

If you want to give it a try you can check his [additions branch](https://github.com/universal/bitwarden-ruby/tree/additions) or you can try my [docker image](https://hub.docker.com/r/mprasil/bitwarden-ruby/) which is using latest Vault and code from additions branch.

**Comment by universal** [comment]
Hello,

I updated my additions branch with the new api changes and it should work now! I'll try to split up the code and submit smaller pull requests! 

Best Johannes

**Comment by raufis27** [comment]
@universal Thank you. Any chance that you can update KeePass script to work with latest API?

**Comment by mprasil** [comment]
Have you tried the Keepass import in Vault? It worked fine last time I've tried.

**Comment by raufis27** [comment]
I can't get Web to work. Can someone share settings.json example ? 
I changed api url to "http://1.....:4567" and "identityUri": "http://1......:33656", (also tried "http://1.....:4567"). But I get this errors:

[Error] XMLHttpRequest cannot load http://1....:4567/connect/token. Preflight response is not successful
[Error] Failed to load resource: Could not connect to the server. (token, line 0)
[Error] XMLHttpRequest cannot load http://...:33656/connect/token due to access control checks.

**Comment by universal** [comment]
## regarding keepass import:
since I'm not using keepass, I'm not interested in it. what you could easily do is check out an older version, import the data and then switch to the current version. Adopting the script is not really complicated and should be possible even if you have little to no knowledge of ruby.

## web vault:
look at my additions branch, there is a tools/compile_webvault.script that adopts the json setting files correctly.

**Comment by raufis27** [comment]
I tried tools/compile_webvault.script. Same problem - [Error] XMLHttpRequest cannot load http://1.....:4567/identity/connect/token. Preflight response is not successful
[Error] Failed to load resource: Preflight response is not successful (token, line 0)
[Error] XMLHttpRequest cannot load http://1....:4567/identity/connect/token. Preflight response is not successful

**Comment by universal** [comment]
@raufis27 the web-vault does not work against this repository currently, you need to use my additions branch if you want it now! and be sure to specify the correct host for your env!

**Comment by raufis27** [comment]
@universal
I am using your branch. I keep posting here because we started conversation here. I did specify correct host... at this point I am not sure what I do wrong. I’ll try docker image later.

**Comment by raufis27** [comment]
@mprasil After adopting bash scripts from your repo I was able to put everything together. I am running test environment under ubuntu server now. Thanks for your help.

**Comment by universal** [comment]
I checked the new web-vault against the current master branch and the basic functionality works out of the box. I hope I will find some time over the next days to document and implement most methods required by the web interface for the management of ciphers / folders.

**Comment by manojchandrashekar** [comment]
@universal Can you share your service URLs?

Currently, I have:

```
apiService.setUrls({
            base: 'https://rubywarden.url',
            api: 'https://rubywarden.url/api',
            identity: 'https://rubywarden.url/identity',
});
```
But the web vault refuses to work. Android app, Firefox/Chrome extensions and the Windows app works fine with the base URL set to `https://rubywarden.url`

**Comment by universal** [comment]
@manojchandrashekar iirc with the latest version of the web vault you don't need to change the urls, if you have the api hosted at the same domain. I put the web vault into the public folder and have sinatra serve that up. I currently only have the code at home and not pushed yet. 

so for me these steps worked:

* git clone "web-vault-repository"
* npm dist:selfhosted (or alike)
* put dist/build into public folder 
* enable static file serving with sinatra for public folder in main app.rb for localhost development
* in production one can serve the static files through nginx / ...

**Comment by manojchandrashekar** [comment]
@universal Thank you. Will try that.
