### ISSUE TITLE
Some identity fields are not saved

### ISSUE THREAD

**Issue by MrClayPole** [jcs/rubywarden#53]
Version 1.2.0
Shell 1.8.4
Renderer 59.0.3071.115
Node 8.2.1
Architecture x64
OS Windows 10 Pro x64

When creating a new identity and hit save the follow fields are not saved: First Name, Middle Name, Last Name, Social Security Number, Passport Number, License Number & Post Code. If I edit the entry they are not visable and if I enter them again and hit save they are also not saved.

**Comment by universal** [comment]
Hello can you check if it works if you apply #47 ? This might fix this!

**Comment by MrClayPole** [comment]
Thanks for the patch. I've manually patched the lib/helper.rb file as per the commit and its now working.

**Comment by universal** [comment]
note  to myself: need to cross-check with the new web-vault if anything in parameter handling changed there.
