### ISSUE TITLE
New Bitwarden 1.6.0 update breaks local connection

### ISSUE THREAD

**Issue by Joshndroid** [jcs/rubywarden#66]
Heads up/PSA

The new bitwarden update V 1.6.0 breaks connection with local rubywarden installation/database.

Popup window seem to say something about 'un expected toaken < within json at position 0'
Within developer console im getting 'POST https:/ipaddress 404 bendor.js:93392 (not found)'

My other boxes with the older version still working flawlessly

Love your work, I'm assuming you maybe already know about this.

**Comment by valantur** [comment]
Yup, I'm also facing the same issue:

"POST /api/accounts/prelogin HTTP/1.1" 404 18 0.0006
And the Chrome extension says "unexpected token < in JSON at position 0" when I try to log in.

Thanks!

**Comment by jcs** [comment]
This should be fixed in 979849f if you want to confirm (make sure to run `rake db:migrate`).

**Comment by valantur** [comment]
Thanks I can log on to the backend now!
Howerver, I found another error when trying to import a csv file generated with my docker instance of bitwarden:

**Comment by Joshndroid** [comment]
@jcs Thanks for your quick work

@valantur I had same issue and seems someone else did as well in #59 with bitwarden import

**Comment by kspearrin** [comment]
@jcs Yes, this will be configurable from the web vault in a future update. If the endpoint 404s the clients will handle it in a backwards compatible way.
