### ISSUE TITLE
Add example import files and tests

### ISSUE THREAD

**Issue by jcs** [jcs/rubywarden#67]
The import tools need to constantly be updated when things change and I have no way to test the fixes.  It would be helpful to have sample import files (CSVs or whatever) that I can use to test each tool.

Since I don't have access to any of these tools anymore, it would be great if people could supply such files.

**Comment by universal** [comment]
I will work on a pull request adding support for the web vault after the attachment #65 pull request. The official web vault provides support for importing from different sources. I wonder if it would be easier to delegate the import to the web vault and use their work and not maintain a custom set of importers that regularly break.

**Comment by Syd** [comment]
what's the end result here? should I submit importer patches or wait until the tests are there, or is the intention to deprecate the importers and focus on the web vault for import?

**Comment by jcs** [comment]
I added tests for the Bitwarden importer in 7c9342a, so I would like similar example files and tests for all of the other importers.
