### ISSUE TITLE
Error importing passwords from keepass

### ISSUE THREAD

**Issue by bahamas10** [jcs/rubywarden#71]
First quick note:

It looks like `rubeepass@3,1.0` has been yanked (this version is in the `Gemfile.lock` file) so I tried using `rubeepass` `3.1.1` and `3.2.0` but had no luck. 

I'm able to successfully run the importer script after doing `bundle install --with keepass`:

```
$ sudo -u rubywarden env RACK_ENV=production bundle exec ruby tools/keepass_import.rb -f /tmp/dave.kdbx -u dave@daveeddy.com
master password for dave@daveeddy.com: 
master password for /tmp/dave.kdbx: 
...
ready to import? [Y/n] y
successfully imported 291 items
```

And I can see all of my folders and logins in the bitwarden firefox plugin (awesome!). However, none of the passwords seem to have been decrypted properly.  Every single entry I look at says:

```
[error: cannot decrypt]
```

for the password.

I'll keep digging into this, but I figure if anyone has any quick ideas what is happening here that would be greatly appreciated.

**Comment by bahamas10** [comment]
I believe this may be an issue with `rubeepass` - I've created https://gitlab.com/mjwhitta/rubeepass/issues/3 with my findings.

**Comment by FloBEAUG** [comment]
Hi,

I have also an issue with keepass importation script : 
`Traceback (most recent call last):
	16: from tools/keepass_import.rb:69:in `<main>'
	15: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:18:in `method_missing'
	14: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:60:in `valid?'
	13: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:60:in `all?'
	12: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:60:in `each'
	11: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:60:in `block in valid?'
	10: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/model_schema.rb:343:in `columns_hash'
	 9: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/model_schema.rb:461:in `load_schema'
	 8: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	 7: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/model_schema.rb:464:in `block in load_schema'
	 6: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
	 5: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/attributes.rb:233:in `load_schema!'
	 4: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/model_schema.rb:471:in `load_schema!'
	 3: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/schema_cache.rb:73:in `columns_hash'
	 2: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/schema_cache.rb:67:in `columns'
	 1: from /var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:167:in `columns'
/var/lib/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:417:in `table_structure': Could not find table 'users' (ActiveRecord::StatementInvalid)`

Using rubeepass 3.1.1 tried with 3.2.0 : same issue.

**Comment by jcs** [comment]
Upstream/OS-specific issue
