### ISSUE TITLE
<h1>Not Found</h1> no matter what I do

### ISSUE THREAD

**Issue by sbogun** [jcs/rubywarden#81]
I followed the README precisely to install rubywarden on my Ubuntu 16.04 machine (also tried MacOS 10.14):
`$ git clone https://github.com/jcs/rubywarden.git`
`$ cd rubywarden/`
`$ bundle install`
`$ mkdir db/production`
`$ env RUBYWARDEN_ENV=production bundle exec rake db:migrate`
`$ env RUBYWARDEN_ENV=production ALLOW_SIGNUPS=1 bundle exec rackup -p 4567 config.ru`

But when I point my browser to `http://127.0.0.1:4567/` I get a 404 (`<h1>Not Found</h1>`).

So I cannot register a user to import 1password data or whatever. What's missing? On the old Bitwarden-ruby this used to work without a charm. 

What's missing? 

Thanks!

**Comment by jcs** [comment]
Rubywarden is just an API server, there is no root action so a 404 is normal on a `GET /`. You need to do things with the desktop app or browser plugins.
