### ISSUE TITLE
Could not find table 'attachments'

### ISSUE THREAD

**Issue by papertigers** [jcs/rubywarden#82]
I recently did a git pull of the repo and ran bundle.

Now when I try to sync or create passwords the logs show

`2018-10-05 16:59:01 - ActiveRecord::StatementInvalid - Could not find table 'attachments':`

If I check via sqlite I can also confirm the table is not there:
```
sqlite> select * from attachments;
Error: no such table: attachments
```

Did I somehow miss a step?  I have previously done the ActiveRecord migration and rubywarden has been running fine.

**Comment by jcs** [comment]
Did you run `rake db:migrate`?

**Comment by papertigers** [comment]
Nope, that's what I somehow missed.
Running `env RUBYWARDEN_ENV=production bundle exec rake db:migrate` from https://github.com/jcs/rubywarden#updating

Thanks again, sorry to bother you!
