### ISSUE TITLE
Add push support for syncing

### ISSUE THREAD

**Issue by tomuta** [jcs/rubywarden#86]
First of all, awesome project! 1000 times better approach than the .net stuff...

Anyway, I noticed that multiple clients don't sync changes automatically.  Looks like it's using websockets for that, as per https://community.bitwarden.com/t/auto-sync-on-all-platformes/355/10

I think the client is trying to set up syncing, but rubywarden doesn't implement that piece:

> "POST /notifications/hub/negotiate HTTP/1.1" 404 18 0.0033

**Comment by fireglow** [comment]
Is there a way to put up a bounty on this? Maybe a few other people could chip in, too.
