### ISSUE TITLE
Dual stack support

### ISSUE THREAD

**Issue by meroujanantonyan** [jcs/rubywarden#87]
Hello,

I am unable to make rubywarden listen on both ipv4 and ipv6.
This cmd is ok for ipv6
 sudo -u rubywarden env RUBYWARDEN_ENV=production ALLOW_SIGNUPS=1 bundle exec rackup -o "::" -p 9080 config.ru
And this one for ipv4
 sudo -u rubywarden env RUBYWARDEN_ENV=production ALLOW_SIGNUPS=1 bundle exec rackup -o "0.0.0.0" -p 9080 config.ru

The first one is supposed to listen on both ipv4 and ipv6..

Thank you

**Comment by jcs** [comment]
That has nothing to do with Rubywarden and would be an issue with Rack.  Regardless, you should probably not be exposing Rack directly to the internet and use something in front of it like nginx.
