### ISSUE TITLE
Allow change KDF iterations in tools/change_master_password.rb

### ISSUE THREAD

**Issue by galaxy001** [jcs/rubywarden#90]
The offical account setting webpage allows user to set KDF iterations.
But the client does not offer any options on master password.

I hope we can modify it here.

**Comment by universal** [comment]
If you want to change it, you could manually change the field in the database on the user record. 

I am still working on web vault compatibility, but right now I'm sadly occupied with other stuff.

**Comment by jcs** [comment]
`tools/change_master_password.rb` will now prompt for KDF iterations, defaulting to the new default of 100,000.
