### ISSUE TITLE
Somehow make it clear to people that they shouldn't contact official Bitwarden support

### ISSUE THREAD

**Issue by kspearrin** [jcs/rubywarden#92]
We frequently get people using these third party servers that contact official support channels for help with problems they are having with it. Lots of times we go back and forth trying to figure out what the problem they are having is only to find out later they are using a third-party server (which they originally fail to mention) and we can't help. This is a drain on resources for the official Bitwarden product. I am not sure what the solution is, but could you brainstorm ideas on how to better communicate to users that they shouldn't do this? I suppose a simple start would be to put a notice in the README or something but I am not sure that is going to solve the problem completely.

Thanks.

**Comment by jcs** [comment]
🤦‍♂️

I can add something more explicit to the README but I thought the existing text would have made it obvious.

Maybe the clients could hit an API endpoint that could return the vendor/version of the server? I'm not sure what kind of automated data is passed along when users contact your support but maybe that version string could be passed along. Or maybe just make it appear in the clients' settings menu so you can ask them to tell you what it reports.

**Comment by kspearrin** [comment]
I am not versed in how this product is deployed, but is there any opportunity to present a notice in the terminal window at some point as well?

I think we can try to keep it simple with just more notices for now to see if the problem gets any better.
