### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by omega123456** [jcs/rubywarden#95]
Attachments dont seem to be saving properly. When you upload one via the browser plugin, it creates the record in the db, but the file blob column is always blank. Hence when you trying to download it, it just returns with a blank file. Seems to be some issue with the part where its trying to retrieve the file content in the routes/attachements.rb, but my ruby knowledge is very limited, so i'm stuck with it.

**Comment by jcs** [comment]
It looks like the URL returned for an attachment has to be absolute.  That change at least gets Bitwarden downloading the attachment.  But then it shows an error, and I'm not sure why.

**Comment by omega123456** [comment]
In my case it doesnt even save the attachment. From what i can tell i should be storing it in the blob field in the table, but its always blank.
