### ISSUE TITLE
[help wanted] HTTPS Support

### ISSUE THREAD

**Issue by hgdfjhgsfjgf** [jcs/rubywarden#97]
This project is incredible.

I was wondering if someone could explain to me if I could set up this server with HTTPS support. I'm a Ruby noob and I don't understand if it should be added to this code or via some other way.

**Comment by omega123456** [comment]
You can set up a webserver that proxies it via https. Can do it with apache or nginx. 

https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by pitr** [comment]
Alternatively, [Cloudflare](https://www.cloudflare.com/) supports free HTTPS support

**Comment by hgdfjhgsfjgf** [comment]
Thank you. It worked.

It works fine with the Chrome extension from BitWarden, but the app give an error: "There is a problem connecting to the server" when I use HTTPS. Is this a bug in the app or in this server?
