### ISSUE TITLE
Import from Enpass?

### ISSUE THREAD

**Issue by Extarys** [jcs/rubywarden#99]
First, thank you for your amazing work! I installed rubywarden with my pihole, they get along well.

Second, I'm a long time user of Enpass and I have ~300 unique passwords saved in there.

I can export in txt or json, but is there an import script I could use that would be compatible with Enpass exported file?

Thanks

**Comment by jcs** [comment]
The [bitwarden importer](https://github.com/jcs/rubywarden/blob/master/tools/bitwarden_import.rb) imports from a CSV, so you could probably just modify that to use the fields in your specific CSV.

**Comment by Extarys** [comment]
I can only export to txt or json. The txt looks like multiple blocks of:

`Title : pexels
Username : something
E-mail : something@someone.com
Password : something
Website : https://www.pexels.com/join/
Note : photo`

Si I guess I will just transfer it to BitWarden every time I log in to something until it's all transferred :)
